// <auto-generated />
namespace Forum_SM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class threadposts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(threadposts));
        
        string IMigrationMetadata.Id
        {
            get { return "201405231220547_threadposts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
